<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="quyentx-w7" name="com.vsii.tsc.TSCSelenium03.quyentx.NewTest" tests="9" failures="1" timestamp="24 Feb 2016 08:10:01 GMT" time="78.382" errors="0">
  <testcase name="selectFlight" time="9.923" classname="com.vsii.tsc.TSCSelenium03.quyentx.NewTest"/>
  <testcase name="findFlight" time="8.283" classname="com.vsii.tsc.TSCSelenium03.quyentx.NewTest"/>
  <testcase name="checkBookFlight" time="14.701" classname="com.vsii.tsc.TSCSelenium03.quyentx.NewTest"/>
  <testcase name="checkFindFlightSuccess" time="7.669" classname="com.vsii.tsc.TSCSelenium03.quyentx.NewTest"/>
  <testcase name="checkBookFlightSuccess" time="14.111" classname="com.vsii.tsc.TSCSelenium03.quyentx.NewTest"/>
  <testcase name="login" time="5.518" classname="com.vsii.tsc.TSCSelenium03.quyentx.NewTest"/>
  <testcase name="checkRegister" time="3.594" classname="com.vsii.tsc.TSCSelenium03.quyentx.NewTest">
    <failure type="java.lang.AssertionError" message="expected [http://newtours.demoaut.com/mercuryregister.php] but found [http://newtours.demoaut.com/create_account_success.php]">
      <![CDATA[java.lang.AssertionError: expected [http://newtours.demoaut.com/mercuryregister.php] but found [http://newtours.demoaut.com/create_account_success.php]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.vsii.tsc.TSCSelenium03.quyentx.NewTest.checkRegister(NewTest.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- checkRegister -->
  <testcase name="checkSelectFlightSuccess" time="9.688" classname="com.vsii.tsc.TSCSelenium03.quyentx.NewTest"/>
  <testcase name="checkLoginSuccess" time="4.895" classname="com.vsii.tsc.TSCSelenium03.quyentx.NewTest"/>
</testsuite> <!-- com.vsii.tsc.TSCSelenium03.quyentx.NewTest -->
